name: alan.rubin
password: 2!EastH977
tenant: HappyValley
ms_tnt_id: b7e3f59e-a6db-46c5-96b3-d1d4cf6910ce
ms_c_s: Mdb8Q~8capaYxH9u5Qz5zfZDJw_UNXNKGLyFHcKc
ms_c_id: 3c5d6b24-d457-44ed-b011-81ef455b934f